// Code generated by struct-scaner tool. DO NOT EDIT.

package rapier // import "https://github.com/things-go/protogen-sabler/cmd/struct-scaner"

func ListStructScan() []any {
	return []any {
		DictItem{},
	}
}