// Code generated by struct-scaner tool. DO NOT EDIT.

package {{ .PackageName }} // import "https://github.com/things-go/protogen-sabler/cmd/struct-scaner"

func {{.FuncName}}() []any {
	return []any {
{{- range $field := .Struct }}
		{{ $field.Name }}{},
{{- end }}
	}
}